# Generated by Django 5.2.3 on 2025-06-20 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="clothingitem",
            name="image",
            field=models.ImageField(blank=True, upload_to="product/%Y/%m/%d"),
        ),
    ]
